rules:
  unpinned-uses:
    ignore:
      - generate-previews.yaml
      - linting.yaml
      - testing.yaml
      - publishing.yaml
  anonymous-definition:
    ignore:
      - 'generate-previews.yaml:27'
      - 'linting.yaml:22'
      - 'publishing.yaml:22'
      - 'publishing.yaml:43'
      - 'publishing.yaml:59'
      - 'testing.yaml:20'
      - 'testing.yaml:53'
  undocumented-permissions:
    ignore:
      - 'generate-previews.yaml:29'
      - 'publishing.yaml:68'
  secrets-outside-env:
    ignore:
      - 'testing.yaml:49'
      - 'testing.yaml:50'
